export const SEARCH_TERM = 'florist'
export const LIMIT_DEFAULT = '20'
export const BASE_URL = 'https://api.yelp.com/v3/businesses/search'
export const API_KEY = 'NCrOnbJiUUw342FD8121BvS1MXqeKxLBExdwPyBpnoiCLVgaG5YUrq_yR7u4ApYXavwMlHfQZhh3-9mPxXfBKr5oBHikCyx7iNjiz-jio2yKahxQQl4WrQdbnPrWXXYx'
export const PROXY_URL = 'https://cors-anywhere.herokuapp.com/'
